# Generated by Django 2.1.3 on 2018-12-06 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0009_auto_20181206_1541'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RFP', '0011_auto_20181128_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTracker',
            fields=[
                ('quotation_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('enquiry_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('enquiry_date', models.CharField(blank=True, max_length=200, null=True)),
                ('price_validity', models.CharField(blank=True, default='30 Days', max_length=200, null=True)),
                ('quoatation_date', models.DateField(auto_now_add=True)),
                ('tc1', models.CharField(blank=True, max_length=200, null=True)),
                ('tc2', models.CharField(blank=True, max_length=200, null=True)),
                ('tc3', models.CharField(blank=True, max_length=200, null=True)),
                ('tc4', models.CharField(blank=True, max_length=200, null=True)),
                ('tc5', models.CharField(blank=True, max_length=200, null=True)),
                ('tc6', models.CharField(blank=True, max_length=200, null=True)),
                ('tc7', models.CharField(blank=True, max_length=200, null=True)),
                ('tc8', models.CharField(blank=True, max_length=200, null=True)),
                ('tc9', models.CharField(blank=True, max_length=200, null=True)),
                ('tc10', models.CharField(blank=True, max_length=200, null=True)),
                ('CustomerContactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.CustomerContactPerson')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.CustomerProfile')),
                ('rfp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
            ],
        ),
    ]
