# Generated by Django 2.1.3 on 2018-12-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotationtracker',
            name='tc9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
