# Generated by Django 2.1.3 on 2018-12-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0002_auto_20181206_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationtracker',
            old_name='CustomerContactPerson',
            new_name='customer_contact_person',
        ),
    ]
