# Generated by Django 2.1.3 on 2018-12-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0003_auto_20181206_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationtracker',
            name='enquiry_date',
        ),
    ]
