# Generated by Django 2.1.3 on 2018-12-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0004_remove_quotationtracker_enquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtracker',
            name='status',
            field=models.CharField(blank=True, default='processing', max_length=200, null=True),
        ),
    ]
