# Generated by Django 2.1.3 on 2018-12-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0005_quotationtracker_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationtracker',
            old_name='quoatation_date',
            new_name='quotation_date',
        ),
    ]
