# Generated by Django 2.1.3 on 2018-12-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0006_auto_20181207_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtracker',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
