# Generated by Django 2.1.3 on 2019-03-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0009_quotationlineitem_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationlineitem',
            name='total_basic_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quotationtracker',
            name='total_basic_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quotationtracker',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
