# Generated by Django 2.1.3 on 2019-03-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0010_auto_20190326_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationlineitem',
            old_name='total_basic_price',
            new_name='basic_price',
        ),
    ]
