# Generated by Django 2.1.3 on 2018-11-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20181109_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gst_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
