# Generated by Django 2.1.3 on 2018-11-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20181109_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontactperson',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
