# Generated by Django 2.1.3 on 2018-11-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_auto_20181109_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
