# Generated by Django 2.1.3 on 2018-12-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_auto_20181110_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='tax_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
