# Generated by Django 2.1.3 on 2018-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_auto_20181206_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='tax_type',
            field=models.CharField(blank=True, default='Normal', max_length=50, null=True),
        ),
    ]
