# Generated by Django 2.1.3 on 2018-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_auto_20181206_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='office_email1',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='office_email2',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='email1',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='email2',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
