# Generated by Django 2.1.3 on 2019-01-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0010_auto_20181218_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryContactPerson',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=200)),
                ('department_name', models.CharField(max_length=200)),
                ('mobileNo1', models.CharField(blank=True, max_length=20, null=True)),
                ('mobileNo2', models.CharField(blank=True, max_length=20, null=True)),
                ('email1', models.EmailField(blank=True, max_length=100, null=True)),
                ('email2', models.EmailField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.CustomerProfile')),
            ],
        ),
    ]
