# Generated by Django 2.1.3 on 2019-03-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0001_initial'),
        ('Customer', '0011_deliverycontactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BankAccount.BankAccountList'),
        ),
    ]
