# Generated by Django 2.1.3 on 2018-11-10 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0006_auto_20181110_1022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('rfp_no', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=200)),
                ('opportunity_status', models.CharField(default='Open', max_length=100)),
                ('enquiry_status', models.CharField(default='Created', max_length=100)),
                ('closing_reason', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.CustomerProfile')),
                ('customer_contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.CustomerContactPerson')),
                ('end_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.EndUser')),
            ],
        ),
        migrations.CreateModel(
            name='RFPApprovalDetail',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('approved_date', models.DateTimeField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
            ],
        ),
        migrations.CreateModel(
            name='RFPAssign1',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('assign_to1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
            ],
        ),
        migrations.CreateModel(
            name='RFPAssign2',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('assign_to2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
            ],
        ),
        migrations.CreateModel(
            name='RFPAssign3',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('assign_to3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
            ],
        ),
        migrations.CreateModel(
            name='RFPCreationDetail',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
            ],
        ),
        migrations.CreateModel(
            name='RFPKeyAccountsDetail',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('key_accounts_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
            ],
        ),
        migrations.CreateModel(
            name='RFPLineitem',
            fields=[
                ('lineitem_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
                ('part_no', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('hsn_code', models.CharField(max_length=10)),
                ('gst', models.FloatField(max_length=200)),
                ('quantity', models.FloatField(max_length=200)),
                ('target_price', models.FloatField(max_length=200)),
                ('remarks', models.TextField(max_length=200)),
                ('customer_lead_time', models.FloatField(max_length=200)),
                ('image', models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('rfp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
            ],
        ),
        migrations.CreateModel(
            name='RFPSourcingDetail',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('completion_date', models.DateTimeField()),
                ('rfp_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP')),
                ('sourcing_completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
