# Generated by Django 2.1.3 on 2018-11-10 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='customer_contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.CustomerContactPerson'),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='end_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.EndUser'),
        ),
    ]
