# Generated by Django 2.1.3 on 2018-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0002_auto_20181110_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='enquiry_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='opportunity_status',
            field=models.CharField(max_length=100),
        ),
    ]
