# Generated by Django 2.1.3 on 2018-11-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0006_auto_20181114_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfplineitem',
            name='customer_lead_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
