# Generated by Django 2.1.3 on 2018-11-16 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0008_auto_20181114_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfpapprovaldetail',
            name='rfp_no',
        ),
        migrations.RemoveField(
            model_name='rfpassign1',
            name='rfp_no',
        ),
        migrations.RemoveField(
            model_name='rfpassign2',
            name='rfp_no',
        ),
        migrations.RemoveField(
            model_name='rfpassign3',
            name='rfp_no',
        ),
        migrations.RemoveField(
            model_name='rfpcreationdetail',
            name='rfp_no',
        ),
        migrations.RemoveField(
            model_name='rfpkeyaccountsdetail',
            name='rfp_no',
        ),
        migrations.RemoveField(
            model_name='rfpsourcingdetail',
            name='rfp_no',
        ),
        migrations.AddField(
            model_name='rfp',
            name='rfp_approval_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RFP.RFPApprovalDetail'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='rfp_assign1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RFP.RFPAssign1'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='rfp_assign2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RFP.RFPAssign2'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='rfp_assign3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RFP.RFPAssign3'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='rfp_creation_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFPCreationDetail'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='rfp_keyaccounts_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RFP.RFPKeyAccountsDetail'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='rfp_sourcing_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RFP.RFPSourcingDetail'),
        ),
    ]
