# Generated by Django 2.1.3 on 2018-11-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0009_auto_20181116_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfpapprovaldetail',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rfpsourcingdetail',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
