# Generated by Django 2.1.3 on 2019-03-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0013_rfp_rfp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp',
            name='document1',
            field=models.FileField(blank=True, null=True, upload_to='rfp/'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='document2',
            field=models.FileField(blank=True, null=True, upload_to='rfp/'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='document3',
            field=models.FileField(blank=True, null=True, upload_to='rfp/'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='document4',
            field=models.FileField(blank=True, null=True, upload_to='rfp/'),
        ),
        migrations.AddField(
            model_name='rfp',
            name='document5',
            field=models.FileField(blank=True, null=True, upload_to='rfp/'),
        ),
    ]
