# Generated by Django 2.1.3 on 2019-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0020_rfp_merge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp',
            name='product_heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
