# Generated by Django 2.1.3 on 2018-12-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sourcing', '0003_sourcinglineitem_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='COQLineitem',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('part_number', models.CharField(blank=True, max_length=200, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=200, null=True)),
                ('moq', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=200, null=True)),
                ('gst', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('uom', models.CharField(max_length=20)),
                ('expected_freight', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(default=15)),
                ('sourcing_lineitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sourcing.SourcingLineitem')),
            ],
        ),
    ]
