# Generated by Django 2.1.3 on 2018-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COQ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coqlineitem',
            name='rfp_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
