# Generated by Django 2.1.3 on 2018-12-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COQ', '0002_coqlineitem_rfp_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='coqlineitem',
            name='lead_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
