# Generated by Django 2.1.3 on 2018-12-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COQ', '0003_coqlineitem_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coqlineitem',
            name='sourcing_lineitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sourcing.SourcingLineitem'),
        ),
    ]
