# Generated by Django 2.1.3 on 2019-03-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COQ', '0004_auto_20181205_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='coqlineitem',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
