# Generated by Django 2.1.3 on 2019-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COQ', '0005_coqlineitem_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coqlineitem',
            name='creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
