# Generated by Django 2.1.3 on 2019-09-18 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Sourcing', '0010_sourcingcharges'),
        ('COQ', '0006_auto_20190320_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCharges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_description', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.FloatField(default=0)),
                ('sourcing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sourcing.Sourcing')),
            ],
        ),
    ]
