# Generated by Django 2.1.3 on 2019-09-19 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COQ', '0007_othercharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercharges',
            name='sourcing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sourcing.Sourcing'),
        ),
    ]
