# Generated by Django 2.1.3 on 2019-09-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0019_auto_20190916_1131'),
        ('COQ', '0008_auto_20190919_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercharges',
            name='sourcing',
        ),
        migrations.AddField(
            model_name='othercharges',
            name='rfp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RFP.RFP'),
        ),
    ]
