# Generated by Django 2.1.3 on 2018-11-05 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_email', models.CharField(blank=True, max_length=100, null=True)),
                ('office_email', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('optional_personal_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('office_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('joining_date', models.DateTimeField(blank=True, null=True)),
                ('leaving_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-user',),
            },
        ),
    ]
