# Generated by Django 2.1.3 on 2018-11-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-designation',)},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
    ]
