# Generated by Django 2.1.3 on 2018-12-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leave_user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
