# Generated by Django 2.1.3 on 2018-12-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_auto_20181221_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='leave_user_type',
            new_name='hr_user_type',
        ),
    ]
