# Generated by Django 2.1.3 on 2019-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20181226_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claim_user_typr',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
