# Generated by Django 2.1.3 on 2019-02-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_profile_claim_user_typr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='claim_user_typr',
            new_name='claim_user_type',
        ),
    ]
