# Generated by Django 2.1.3 on 2019-06-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_profile_supplier_payment_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpo_editing',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
