# Generated by Django 2.1.3 on 2019-11-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_profile_customer_editing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='creating_customer',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
