# Generated by Django 2.1.3 on 2019-03-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpotracker',
            name='vpo_type',
            field=models.CharField(default='Regular', max_length=50),
        ),
    ]
