# Generated by Django 2.1.3 on 2019-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0002_vendorpotracker_vpo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpolineitems',
            name='total_basic_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendorpolineitems',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendorpotracker',
            name='basic_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendorpotracker',
            name='total_value',
            field=models.FloatField(default=0),
        ),
    ]
