# Generated by Django 2.1.3 on 2019-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0003_auto_20190326_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpolineitems',
            name='actual_price',
            field=models.FloatField(default=0),
        ),
    ]
