# Generated by Django 2.1.3 on 2019-03-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0005_vendorpotracker_all_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpotracker',
            name='order_status',
            field=models.CharField(default='Order Preparing', max_length=100),
        ),
    ]
