# Generated by Django 2.1.3 on 2019-03-29 04:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0006_vendorpotracker_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPOStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='vendorpotracker',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpostatus',
            name='vpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POForVendor.VendorPOTracker'),
        ),
    ]
