# Generated by Django 2.1.3 on 2019-04-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0008_auto_20190402_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpo',
            name='advance_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vendorpo',
            name='payment_term',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
