# Generated by Django 2.1.3 on 2019-04-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0010_vpostatus_update_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpolineitems',
            name='receivable_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
