# Generated by Django 2.1.3 on 2019-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0011_vendorpolineitems_receivable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpolineitems',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
