# Generated by Django 2.1.3 on 2019-04-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0012_vendorpolineitems_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpolineitems',
            name='cpo_lineitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CPOLineitem'),
        ),
    ]
