# Generated by Django 2.1.3 on 2019-04-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0013_auto_20190419_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyIndex',
            fields=[
                ('currency', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('currency_symbol', models.CharField(max_length=20)),
                ('currency_code', models.CharField(max_length=20)),
            ],
        ),
    ]
