# Generated by Django 2.1.3 on 2019-04-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0014_currencyindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpo',
            name='inr_value',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='vendorpo',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POForVendor.CurrencyIndex'),
        ),
    ]
