# Generated by Django 2.1.3 on 2019-04-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0016_auto_20190420_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpo',
            name='currency',
            field=models.ForeignKey(default='Indian Rupees', on_delete=django.db.models.deletion.CASCADE, to='POForVendor.CurrencyIndex'),
        ),
    ]
