# Generated by Django 2.1.3 on 2019-04-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0018_auto_20190420_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpotracker',
            name='non_inr_value',
            field=models.FloatField(default=0),
        ),
    ]
