# Generated by Django 2.1.3 on 2019-04-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0021_vpopaymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpopaymentrequest',
            name='vpo',
        ),
        migrations.DeleteModel(
            name='VPOPaymentRequest',
        ),
    ]
