# Generated by Django 2.1.3 on 2019-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0024_auto_20190506_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpo',
            name='creation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
