# Generated by Django 2.1.3 on 2019-06-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0027_paymentterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpo',
            name='payment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='POForVendor.PaymentTerms'),
        ),
    ]
