# Generated by Django 2.1.3 on 2019-06-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0030_auto_20190620_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentterms',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendorpo',
            name='payment_option',
        ),
        migrations.DeleteModel(
            name='PaymentTerms',
        ),
    ]
