# Generated by Django 2.1.3 on 2019-06-22 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0032_auto_20190620_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorpo',
            name='cpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='POFromCustomer.CustomerPO'),
        ),
        migrations.AlterField(
            model_name='vendorpo',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorpo',
            name='vendor_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Supplier.SupplierContactPerson'),
        ),
        migrations.AlterField(
            model_name='vendorpolineitems',
            name='cpo_lineitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='POFromCustomer.CPOLineitem'),
        ),
        migrations.AlterField(
            model_name='vendorpotracker',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
