# Generated by Django 2.1.3 on 2019-10-22 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('POForVendor', '0033_auto_20190622_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiatedAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='negotiated_quotation/')),
                ('quotation_link', models.TextField(blank=True, null=True)),
                ('vpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POForVendor.VendorPO')),
            ],
        ),
    ]
