# Generated by Django 2.1.3 on 2019-02-13 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POFromCustomer', '0010_cpolineitem_segment_status'),
        ('Supplier', '0002_auto_20181218_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('po_number', models.TextField(blank=True, null=True, unique=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('payment_term', models.IntegerField(default=0)),
                ('advance_percentage', models.IntegerField(default=0)),
                ('freight_charges', models.FloatField(default=0.0)),
                ('custom_duties', models.FloatField(default=0.0)),
                ('mode_of_transport', models.CharField(blank=True, max_length=200, null=True)),
                ('insurance', models.CharField(blank=True, max_length=200, null=True)),
                ('inco_terms', models.CharField(blank=True, max_length=200, null=True)),
                ('installation', models.CharField(blank=True, max_length=200, null=True)),
                ('pf', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(default='INR', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('di1', models.TextField(blank=True, null=True)),
                ('di2', models.TextField(blank=True, null=True)),
                ('di3', models.TextField(blank=True, null=True)),
                ('di4', models.TextField(blank=True, null=True)),
                ('di5', models.TextField(blank=True, null=True)),
                ('di6', models.TextField(blank=True, null=True)),
                ('di7', models.TextField(blank=True, null=True)),
                ('di8', models.TextField(blank=True, null=True)),
                ('di9', models.TextField(blank=True, null=True)),
                ('di10', models.TextField(blank=True, null=True)),
                ('cpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CustomerPO')),
            ],
        ),
        migrations.CreateModel(
            name='VPOLineitems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=10, null=True)),
                ('gst', models.FloatField(blank=True, null=True)),
                ('uom', models.CharField(default='Pcs', max_length=20)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('cpo_lineitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CPOLineitem')),
            ],
        ),
        migrations.CreateModel(
            name='VPOReceiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VPORequester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vpo',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POToVendor.VPOReceiver'),
        ),
        migrations.AddField(
            model_name='vpo',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POToVendor.VPORequester'),
        ),
        migrations.AddField(
            model_name='vpo',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.SupplierProfile'),
        ),
        migrations.AddField(
            model_name='vpo',
            name='vendor_contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.SupplierContactPerson'),
        ),
    ]
