# Generated by Django 2.1.3 on 2019-02-13 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0010_cpolineitem_segment_status'),
        ('POToVendor', '0002_auto_20190213_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPOLineitems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=10, null=True)),
                ('gst', models.FloatField(blank=True, null=True)),
                ('uom', models.CharField(default='Pcs', max_length=20)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('cpo_lineitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CPOLineitem')),
                ('vpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POToVendor.VPO')),
            ],
        ),
    ]
