# Generated by Django 2.1.3 on 2019-02-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0003_vpolineitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpo',
            name='pf',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
