# Generated by Django 2.1.3 on 2019-02-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0004_auto_20190215_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpo',
            name='pf',
            field=models.FloatField(blank=True, default=0.0, max_length=200, null=True),
        ),
    ]
