# Generated by Django 2.1.3 on 2019-02-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0005_auto_20190215_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpo',
            name='pf',
            field=models.FloatField(default=0.0),
        ),
    ]
