# Generated by Django 2.1.3 on 2019-02-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0008_auto_20190223_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpo',
            name='receiver',
        ),
        migrations.AddField(
            model_name='vpo',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vpo',
            name='receiver_phone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vpo',
            name='receiver_phone2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
