# Generated by Django 2.1.3 on 2019-03-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0009_auto_20190228_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpo',
            name='receiver_dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vpo',
            name='receiver_phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
