# Generated by Django 2.1.3 on 2019-03-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0010_auto_20190301_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpo',
            name='po_status',
            field=models.CharField(default='Preparing', max_length=50),
        ),
        migrations.AlterField(
            model_name='vpo',
            name='di1',
            field=models.TextField(default='Original Invoice & Delivery Challans Four (4) copies each must be submitted at the time of delivery of goods'),
        ),
        migrations.AlterField(
            model_name='vpo',
            name='di2',
            field=models.TextField(default='Entire Goods must be delivered in Single Lot if not specified otherwise. For any changes, must inform IMMEDIATELY.'),
        ),
        migrations.AlterField(
            model_name='vpo',
            name='di3',
            field=models.TextField(default='Product Specifications, Qty, Price, Delivery Terms are in accordance with your offer'),
        ),
        migrations.AlterField(
            model_name='vpo',
            name='di4',
            field=models.TextField(default='Product Specifications, Qty, Price, Delivery Terms shall remain unchanged for this order.'),
        ),
        migrations.AlterField(
            model_name='vpo',
            name='di5',
            field=models.TextField(default='Notify any delay in shipment as scheduled IMMEDIATELY.'),
        ),
        migrations.AlterField(
            model_name='vpo',
            name='di6',
            field=models.TextField(default='Mail all correspondance to corporate office address only.'),
        ),
        migrations.AlterField(
            model_name='vpo',
            name='di7',
            field=models.TextField(default='Must Submit Warranty Certificate, PO copy, TC copy (if any) and all other documents as per standard documentation'),
        ),
    ]
