# Generated by Django 2.1.3 on 2019-03-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0011_auto_20190301_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpolineitems',
            name='discount',
        ),
        migrations.AddField(
            model_name='vpo',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
