# Generated by Django 2.1.3 on 2019-03-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0012_auto_20190301_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpo',
            name='po_date',
        ),
        migrations.RemoveField(
            model_name='vpo',
            name='po_number',
        ),
    ]
