# Generated by Django 2.1.3 on 2019-03-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0013_auto_20190301_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPOTracker',
            fields=[
                ('po_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('po_date', models.DateField()),
                ('vpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POToVendor.VPO')),
            ],
        ),
    ]
