# Generated by Django 2.1.3 on 2019-03-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0014_vpotracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpotracker',
            name='po_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
