# Generated by Django 2.1.3 on 2019-03-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0015_auto_20190304_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpotracker',
            name='status',
            field=models.CharField(default='Requested', max_length=50),
        ),
    ]
