# Generated by Django 2.1.3 on 2019-03-05 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0018_vpotracker_requester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vporeceiver',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='vporequester',
            name='requester',
        ),
        migrations.AlterField(
            model_name='vpo',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='VPOReceiver',
        ),
        migrations.DeleteModel(
            name='VPORequester',
        ),
    ]
