# Generated by Django 2.1.3 on 2019-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0022_auto_20190314_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpo',
            name='terms_of_payment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
