# Generated by Django 2.1.3 on 2019-05-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POToVendor', '0023_vpo_terms_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpo',
            name='cpo',
        ),
        migrations.RemoveField(
            model_name='vpo',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='vpo',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vpo',
            name='vendor_contact_person',
        ),
        migrations.RemoveField(
            model_name='vpolineitems',
            name='cpo_lineitem',
        ),
        migrations.RemoveField(
            model_name='vpolineitems',
            name='vpo',
        ),
        migrations.RemoveField(
            model_name='vpotracker',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='vpotracker',
            name='vpo',
        ),
        migrations.DeleteModel(
            name='VPO',
        ),
        migrations.DeleteModel(
            name='VPOLineitems',
        ),
        migrations.DeleteModel(
            name='VPOTracker',
        ),
    ]
