# Generated by Django 2.1.3 on 2019-04-11 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POForVendor', '0011_vendorpolineitems_receivable_quantity'),
        ('Supplier', '0002_auto_20181218_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNLineitem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True)),
                ('pack_size', models.CharField(blank=True, max_length=10, null=True)),
                ('uom', models.CharField(default='Pcs', max_length=20)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField(default=0)),
                ('gst', models.FloatField(blank=True, default=0, null=True)),
                ('total_basic_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GRNTracker',
            fields=[
                ('grn_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='creation_in_progress', max_length=50, null=True)),
                ('grn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.SupplierProfile')),
                ('vpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POForVendor.VendorPOTracker')),
            ],
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRNIR.GRNTracker'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='vpo_lineitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POForVendor.VendorPOLineitems'),
        ),
    ]
