# Generated by Django 2.1.3 on 2019-05-15 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GRNIR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('document_no', models.CharField(blank=True, max_length=100, null=True)),
                ('document_date', models.DateField()),
                ('attachment', models.FileField(upload_to='grn_document/')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRNIR.GRNTracker')),
            ],
        ),
    ]
