# Generated by Django 2.1.3 on 2019-05-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRNIR', '0002_grnattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grntracker',
            name='ir_status',
            field=models.CharField(blank=True, default='incomplete', max_length=50, null=True),
        ),
    ]
