# Generated by Django 2.1.3 on 2019-05-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0023_cpolineitem_pending_po_releasing_quantity'),
        ('GRNIR', '0003_grntracker_ir_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnlineitem',
            name='cpo_lineitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CPOLineitem'),
        ),
        migrations.AddField(
            model_name='grntracker',
            name='cpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CustomerPO'),
        ),
    ]
