# Generated by Django 2.1.3 on 2019-06-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRNIR', '0005_auto_20190522_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='irtracker',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grntracker',
            name='cpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='POFromCustomer.CustomerPO'),
        ),
        migrations.AlterField(
            model_name='grntracker',
            name='vpo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='POForVendor.VendorPOTracker'),
        ),
    ]
