# Generated by Django 2.1.3 on 2019-07-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRNIR', '0006_auto_20190624_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='grntracker',
            name='grn_type',
            field=models.CharField(default='regular', max_length=30),
        ),
    ]
