# Generated by Django 2.1.3 on 2019-07-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRNIR', '0007_grntracker_grn_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnlineitem',
            name='invoiced_quantity',
            field=models.FloatField(default=0),
        ),
    ]
