# Generated by Django 2.1.3 on 2019-03-22 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_holder', models.CharField(max_length=200)),
                ('ifcs_code', models.CharField(max_length=200)),
            ],
        ),
    ]
