# Generated by Django 2.1.3 on 2019-06-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0002_vendorbankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbankaccount',
            name='acknowledgement',
        ),
    ]
