# Generated by Django 2.1.3 on 2019-09-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0003_remove_vendorbankaccount_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountlist',
            name='account_number',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='bankaccountlist',
            name='account_type',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
