# Generated by Django 2.1.3 on 2018-11-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcinglineitem',
            name='expected_freight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
