# Generated by Django 2.1.3 on 2019-03-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sourcing', '0003_sourcinglineitem_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sourcing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sourcing.Sourcing')),
            ],
        ),
    ]
