# Generated by Django 2.1.3 on 2019-03-15 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('RFP', '0014_auto_20190314_0746'),
        ('Sourcing', '0004_rfq'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQLineitem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfp_lineitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RFP.RFPLineitem')),
            ],
        ),
        migrations.AddField(
            model_name='rfq',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfqlineitem',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sourcing.RFQ'),
        ),
    ]
