# Generated by Django 2.1.3 on 2019-03-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sourcing', '0006_auto_20190318_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcinglineitem',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
