# Generated by Django 2.1.3 on 2019-09-16 10:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Sourcing', '0008_auto_20190320_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='supplier_quotation/')),
                ('quotation_link', models.TextField(blank=True, null=True)),
                ('sourcing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sourcing.Sourcing')),
            ],
        ),
    ]
