# Generated by Django 2.1.3 on 2019-10-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sourcing', '0010_sourcingcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcing',
            name='delivery_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
