# Generated by Django 2.1.3 on 2019-10-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sourcing', '0011_sourcing_delivery_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcing',
            name='delivery_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
