# Generated by Django 2.1.3 on 2019-11-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sourcing', '0012_auto_20191017_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcing',
            name='offer_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
