# Generated by Django 2.1.3 on 2019-01-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpo',
            name='status',
            field=models.CharField(default='creation_inprogress', max_length=100),
        ),
    ]
