# Generated by Django 2.1.3 on 2019-02-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0003_cposelectedquotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cposelectedquotation',
            old_name='CustomerPO',
            new_name='customer_po',
        ),
    ]
