# Generated by Django 2.1.3 on 2019-02-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0006_auto_20190211_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpo',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
