# Generated by Django 2.1.3 on 2019-02-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0007_customerpo_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpoassign',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='customerpo',
            name='cpo_assign_detail',
        ),
        migrations.DeleteModel(
            name='CPOAssign',
        ),
    ]
