# Generated by Django 2.1.3 on 2019-02-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0009_auto_20190212_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpolineitem',
            name='segment_status',
            field=models.BooleanField(default=False),
        ),
    ]
