# Generated by Django 2.1.3 on 2019-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0010_cpolineitem_segment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpo',
            name='segmentation',
            field=models.BooleanField(default=False),
        ),
    ]
