# Generated by Django 2.1.3 on 2019-03-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0011_customerpo_segmentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpo',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpo',
            name='customer_po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpo',
            name='customer_po_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerpo',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpo',
            name='inco_terms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerpo',
            name='payment_terms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customerpo',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
