# Generated by Django 2.1.3 on 2019-03-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0014_auto_20190321_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpo',
            name='po_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
