# Generated by Django 2.1.3 on 2019-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0015_customerpo_po_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpo',
            name='total_value',
            field=models.FloatField(default=0),
        ),
    ]
