# Generated by Django 2.1.3 on 2019-03-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0016_customerpo_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpolineitem',
            name='basic_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cpolineitem',
            name='gst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
