# Generated by Django 2.1.3 on 2019-03-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0017_auto_20190326_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpolineitem',
            old_name='basic_price',
            new_name='total_basic_price',
        ),
    ]
