# Generated by Django 2.1.3 on 2019-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0018_auto_20190326_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpo',
            name='lineitem_copy_status',
            field=models.BooleanField(default=False),
        ),
    ]
