# Generated by Django 2.1.3 on 2019-04-03 08:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0019_customerpo_lineitem_copy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingQuantity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pending_quantity', models.FloatField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cpolineitem',
            name='pending_delivery_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingquantity',
            name='cpo_lineitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CPOLineitem'),
        ),
    ]
