# Generated by Django 2.1.3 on 2019-04-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0020_auto_20190403_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingquantity',
            name='cpo_lineitem',
        ),
        migrations.DeleteModel(
            name='PendingQuantity',
        ),
    ]
