# Generated by Django 2.1.3 on 2019-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0021_auto_20190403_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpolineitem',
            name='pending_delivery_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
