# Generated by Django 2.1.3 on 2019-04-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0022_auto_20190403_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpolineitem',
            name='pending_po_releasing_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
