# Generated by Django 2.1.3 on 2019-05-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0023_cpolineitem_pending_po_releasing_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpolineitem',
            name='direct_receivable_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
