# Generated by Django 2.1.3 on 2019-05-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0024_cpolineitem_direct_receivable_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpolineitem',
            name='quotation_lineitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quotation.QuotationLineitem'),
        ),
    ]
