# Generated by Django 2.1.3 on 2019-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0026_auto_20190622_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpo',
            name='processing_type',
            field=models.CharField(default='direct', max_length=100),
        ),
    ]
