# Generated by Django 2.1.3 on 2019-09-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0027_customerpo_processing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpolineitem',
            name='processing_type',
            field=models.CharField(default='direct', max_length=200),
        ),
    ]
