# Generated by Django 2.1.3 on 2019-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POFromCustomer', '0029_cpolineitem_indirect_processing_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpo',
            name='product_heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
