# Generated by Django 2.1.3 on 2019-01-02 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('document', models.FileField(upload_to='static/doc/claim/')),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstClaimTypes',
            fields=[
                ('claim_type1', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SecondClaimTypes',
            fields=[
                ('claim_type2', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('claim_type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expences.FirstClaimTypes')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdClaimTypes',
            fields=[
                ('claim_type3', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('claim_type2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expences.SecondClaimTypes')),
            ],
        ),
        migrations.AddField(
            model_name='claimdetails',
            name='claim_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expences.ThirdClaimTypes'),
        ),
        migrations.AddField(
            model_name='claimdetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
