# Generated by Django 2.1.3 on 2019-01-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetails',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='claimdetails',
            name='status',
            field=models.CharField(default='Requested', max_length=200),
        ),
    ]
