# Generated by Django 2.1.3 on 2019-01-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expences', '0002_auto_20190103_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetails',
            name='document',
            field=models.FileField(upload_to='claim/'),
        ),
    ]
