# Generated by Django 2.1.3 on 2019-02-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expences', '0003_auto_20190107_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimdetails',
            old_name='amount',
            new_name='total_basic_amount',
        ),
        migrations.AddField(
            model_name='claimdetails',
            name='applicable_gst_value',
            field=models.FloatField(default=0),
        ),
    ]
