# Generated by Django 2.1.3 on 2019-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expences', '0004_auto_20190204_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetails',
            name='document',
            field=models.FileField(default='claim/none.jpg', upload_to='claim/'),
        ),
    ]
