# Generated by Django 2.1.3 on 2019-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expences', '0005_auto_20190219_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetails',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='claim/'),
        ),
    ]
