# Generated by Django 2.1.3 on 2018-12-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0002_auto_20181221_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicableleaves',
            old_name='user',
            new_name='employee',
        ),
    ]
