# Generated by Django 2.1.3 on 2018-12-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0003_auto_20181221_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='user',
            new_name='employee',
        ),
    ]
