# Generated by Django 2.1.3 on 2018-12-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0004_auto_20181221_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='Requested', max_length=50),
        ),
    ]
