# Generated by Django 2.1.3 on 2018-12-24 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0005_auto_20181224_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicableleaves',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
