# Generated by Django 2.1.3 on 2018-12-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaves', '0006_auto_20181224_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
