# Generated by Django 2.1.3 on 2018-11-19 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContactPerson',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mobileNo1', models.CharField(blank=True, max_length=20, null=True)),
                ('mobileNo2', models.CharField(blank=True, max_length=20, null=True)),
                ('email1', models.EmailField(blank=True, max_length=50, null=True)),
                ('email2', models.EmailField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('office_email1', models.EmailField(blank=True, max_length=20, null=True)),
                ('office_email2', models.EmailField(blank=True, max_length=20, null=True)),
                ('office_phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('office_phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('payment_term', models.IntegerField(blank=True, null=True)),
                ('advance_persentage', models.IntegerField(blank=True, null=True)),
                ('inco_term', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='suppliercontactperson',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.SupplierProfile'),
        ),
    ]
