# Generated by Django 2.1.3 on 2019-11-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_auto_20181218_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
