# Generated by Django 2.1.3 on 2019-11-19 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_supplierprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(upload_to='grn_document/')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.SupplierProfile')),
            ],
        ),
    ]
