# Generated by Django 2.1.3 on 2019-03-30 04:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POFromCustomer', '0019_customerpo_lineitem_copy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pending_quantity', models.FloatField()),
                ('cpo_lineitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CPOLineitem')),
            ],
        ),
    ]
