# Generated by Django 2.1.3 on 2019-03-30 07:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_customerprofile_bank_account'),
        ('POFromCustomer', '0019_customerpo_lineitem_copy_status'),
        ('Invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineitem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('part_number', models.CharField(blank=True, max_length=200, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.FloatField(default=1)),
                ('uom', models.CharField(default='PC', max_length=20)),
                ('unit_price', models.FloatField(default=0)),
                ('total_basic_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceTracker',
            fields=[
                ('invoice_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('po_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('basic_value', models.FloatField(default=0)),
                ('total_value', models.FloatField(default=0)),
                ('generating_status', models.CharField(default='Creation_in_progress', max_length=200)),
                ('cpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='POFromCustomer.CustomerPO')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.CustomerProfile')),
                ('customer_contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.CustomerContactPerson')),
            ],
        ),
        migrations.AlterField(
            model_name='pendingdelivery',
            name='pending_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoice.InvoiceTracker'),
        ),
    ]
