# Generated by Django 2.1.3 on 2019-03-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_invoicetracker_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicetracker',
            name='generating_status',
            field=models.CharField(default='creation_in_progress', max_length=200),
        ),
    ]
