# Generated by Django 2.1.3 on 2019-04-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0004_auto_20190330_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetracker',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
