# Generated by Django 2.1.3 on 2019-04-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0005_invoicetracker_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetracker',
            name='po_reference',
        ),
    ]
