# Generated by Django 2.1.3 on 2019-08-01 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('GRNIR', '0008_grnlineitem_invoiced_quantity'),
        ('Invoice', '0008_auto_20190801_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceGRNLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0.0)),
                ('grn_lineitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GRNIR.GRNLineitem')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='grn_lineitem',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='supplier_po_lineitem',
        ),
        migrations.AddField(
            model_name='invoicegrnlink',
            name='invoice_lineitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.InvoiceLineitem'),
        ),
    ]
