# Generated by Django 2.1.3 on 2019-08-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0009_auto_20190801_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetracker',
            name='other_info1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='other_info2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='other_info3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='other_info4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='other_info5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='other_info6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='other_info7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='receiver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='receiver_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='receiver_phone_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='requester',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='requester_phone_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
