# Generated by Django 2.1.3 on 2019-08-21 12:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0010_auto_20190806_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to='invoice_ack/')),
            ],
        ),
        migrations.AddField(
            model_name='invoicetracker',
            name='acknowledgement',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='acknowledgedocument',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoice.InvoiceTracker'),
        ),
    ]
