# Generated by Django 2.1.3 on 2019-09-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0011_auto_20190821_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdelivery',
            name='pending_indirect_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
