# Generated by Django 2.1.3 on 2019-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0012_pendingdelivery_pending_indirect_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicegrnlink',
            name='grn_link_type',
            field=models.CharField(default='direct', max_length=10),
        ),
    ]
