# Generated by Django 2.1.3 on 2019-04-27 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POForVendor', '0023_vendorpotracker_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='supplier_payment/')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='supplier_payment/')),
                ('attachment3', models.FileField(blank=True, null=True, upload_to='supplier_payment/')),
                ('payment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Requested', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='supplier_payment_request/')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='supplier_payment_request/')),
                ('attachment3', models.FileField(blank=True, null=True, upload_to='supplier_payment_request/')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POForVendor.VendorPOTracker')),
            ],
        ),
        migrations.AddField(
            model_name='supplierpaymentinfo',
            name='payment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupplierPayment.SupplierPaymentRequest'),
        ),
    ]
