# Generated by Django 2.1.3 on 2019-06-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankAccount', '0002_vendorbankaccount'),
        ('SupplierPayment', '0002_auto_20190503_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpaymentinfo',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankAccount.VendorBankAccount'),
        ),
        migrations.AddField(
            model_name='supplierpaymentinfo',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
