# Generated by Django 2.1.3 on 2019-06-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierPayment', '0003_auto_20190628_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpaymentinfo',
            name='acknowledgement',
            field=models.CharField(default='no', max_length=200),
        ),
    ]
