# Generated by Django 2.1.3 on 2019-07-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierPayment', '0004_supplierpaymentinfo_acknowledgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpaymentinfo',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
