# Generated by Django 2.1.3 on 2018-11-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateList',
            fields=[
                ('state_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
